local locale = GLOBAL.LOC.GetLocaleCode()

if locale == 'zh' or locale == 'zhr' or locale == 'zhr' then
    GLOBAL.STRINGS.NAMES.SCYTHE = "镰刀"
    GLOBAL.STRINGS.RECIPE_DESC.SCYTHE = "砍倒成群的敌人!"
    GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SCYTHE = "砍倒成群的敌人!"


    GLOBAL.STRINGS.NAMES.SCYTHE_GOLDEN = "黄金镰刀" --剽殷鎺菛灆
    GLOBAL.STRINGS.RECIPE_DESC.SCYTHE_GOLDEN = "更加有效的采集!"
    GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SCYTHE_GOLDEN = "更加有效的采集!"
    GLOBAL.STRINGS.ACTIONS.MOWDOWN  = "收割"
end